### PR TITLE
fix: ensure alias is set to branch

### PR DESCRIPTION
**Pull request by sastan**
This PR ensures to always set the alias url output to point to the branch url by replacing the hash in the deployment url with the branch name.

### CODE REVIEW

**Comment by WalshyDev** [comment]
This won't always work. Ideally, we just remove the race condition instead or have it exposed regardless. I'll leave this open for now

**Comment by jasikpark** [comment]
++ to fixing this - we use direct uploads & pass a branch name, resulting in `url === alias` on most runs

I'll just hardcode the url myself for now...

**Comment by jasikpark** [comment]
ah, hardcoding has some caveats since. it needs to be url encoded somehow + cf truncates branch names in the subdomain

**Comment by Hanawa02** [comment]
Would it be possible to pass the alias instead?

**Comment by nprogers** [comment]
Thank you for your help in maintaining this repository 🧡. We've migrated to [wrangler-action](https://github.com/cloudflare/wrangler-action) and are making improvements to ensure that contributions like this will be more easily integrated and better supported. Please come join us at wrangler-action, and thank you again for your support.

**Pull request closed without merging**
