### PR TITLE
Fix nodejs deprecated warning

### PR DESCRIPTION
**Pull request by riderx**
This Pr fix the issue about deprecated warning reference from https://github.com/cloudflare/pages-action/issues/117

### CODE REVIEW

**Review by marmikdesai — APPROVED** [review]

**Comment by cagataygurturk** [comment]
Any ETA for its release?

**Review by antonio-gg-dev — APPROVED** [review]

**Review by Chemaclass — APPROVED** [review]

**Review by JesusValeraDev — APPROVED** [review]

**Review by harryzcy — APPROVED** [review]

**Review by linhub15 — APPROVED** [review]

**Comment by andykenward** [comment]
@riderx can we also update the build cli [esbuild target](https://esbuild.github.io/api/#target) from `es2021` to `node20`?

## From
https://github.com/cloudflare/pages-action/blob/aeb0d936a7e08b4861c3d0ac8811fe39138085f9/package.json#L7


## To
```json
"build": "npx esbuild src/index.ts --bundle --platform=node --target=node20 --outfile=index.js",
```

**Review by Goooler — APPROVED** [review]
And you can update the description to 

Closes #117.

That issue will be closed once this PR gets merged.

**Comment by benminer** [comment]
Any reason this hasn't been merged yet?

**Comment by Fabio1988** [comment]
what's the blocker of this?

**Comment by riderx** [comment]
Thanks @andykenward i modified it!
I'm not a core contributor, so I cannot do much more than a PR

**Comment by riderx** [comment]
Maybe @WalshyDev if you can report internally it, it would me super nice <3

**Comment by WalshyDev** [comment]
cc: @cloudflare/banda-team

**Comment by andykenward** [comment]
Also need to update `@types/node` to 20. Plus we can remove the usage of the NPM package `"undici"` for `fetch` as Node.js 20 supports `fetch` natively.

**Comment by Chemaclass** [comment]
What is preventing merging this PR?

**Review by KuznetsovNikita — APPROVED** [review]

**Comment by linhub15** [comment]
> Is there any reason this hasn't been merged yet?

This repo is going to be deprecated. https://github.com/cloudflare/pages-action/issues/131

Use `wrangler-action` instead to deploy pages.
https://github.com/cloudflare/wrangler-action?tab=readme-ov-file#deploy-your-pages-site-production--preview

**Comment by nprogers** [comment]
Thank you for your help in maintaining this repository 🧡. We've migrated to [wrangler-action](https://github.com/cloudflare/wrangler-action) and are making improvements to ensure that contributions like this will be more easily integrated and better supported. Please come join us at wrangler-action!

**Pull request closed without merging**
